# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_auto_20180723_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetype',
            name='name',
            field=models.CharField(choices=[('collection', 'collection'), ('blog-article', 'blog-article'), ('event', 'event'), ('interview', 'interview'), ('labs-post', 'labs-post'), ('press-package', 'press-package'), ('digest', 'digest')], max_length=255, primary_key=True, serialize=False),
        ),
    ]
