# Generated by Django 3.2.16 on 2023-01-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_auto_20180926_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetype',
            name='name',
            field=models.CharField(choices=[('blog-article', 'blog-article'), ('collection', 'collection'), ('digest', 'digest'), ('event', 'event'), ('interview', 'interview'), ('labs-post', 'labs-post'), ('press-package', 'press-package')], max_length=255, primary_key=True, serialize=False),
        ),
    ]
