# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-05-17 05:54


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0014_auto_20170516_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='source',
            field=models.CharField(choices=[(b'crossref', b'Crossref'), (b'pubmed', b'PubMed Central'), (b'scopus', b'Scopus')], max_length=10),
        ),
    ]
