# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-11 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0015_auto_20170517_0554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('pattern', models.CharField(help_text=b'regex used to generate GA queries', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text=b'fully resolved path using linked pattern.', max_length=255)),
                ('count', models.PositiveIntegerField(help_text=b'total sessions since ever')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrics.Page')),
            ],
        ),
    ]
