# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-22 01:58
from __future__ import unicode_literals

import article_metrics.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('article_metrics', '0001_initial'), ('article_metrics', '0002_auto_20150918_1516'), ('article_metrics', '0003_rename_metric_type'), ('article_metrics', '0004_auto_20150921_1014'), ('article_metrics', '0005_auto_20150921_1541'), ('article_metrics', '0006_auto_20150921_1545'), ('article_metrics', '0007_auto_20150925_1630'), ('article_metrics', '0008_auto_20170125_1758'), ('article_metrics', '0009_auto_20170130_1756'), ('article_metrics', '0010_auto_20170131_1854'), ('article_metrics', '0011_auto_20170201_1835'), ('article_metrics', '0012_auto_20170224_0633'), ('article_metrics', '0013_auto_20170322_0339'), ('article_metrics', '0014_auto_20170516_0531'), ('article_metrics', '0015_auto_20170517_0554'), ('article_metrics', '0016_auto_20180205_0102')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi', models.CharField(help_text='article identifier', max_length=255)),
            ],
            options={
                'db_table': 'metrics_article',
            },
        ),
        migrations.CreateModel(
            name='GAMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, help_text="the date this metric is for in YYYY-MM-DD, YYYY-MM and YYYY formats or None for 'all time'", max_length=10, null=True)),
                ('type', models.CharField(choices=[('day', 'Daily'), ('month', 'Monthly'), ('year', 'Yearly'), ('ever', 'All time')], max_length=10)),
                ('full', models.PositiveSmallIntegerField(help_text='article page views')),
                ('abstract', models.PositiveSmallIntegerField(help_text='article abstract page views')),
                ('digest', models.PositiveSmallIntegerField(help_text='article digest page views')),
                ('pdf', models.PositiveSmallIntegerField(help_text='pdf downloads')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article_metrics.Article')),
            ],
            options={
                'db_table': 'metrics_metric',
            },
        ),
        migrations.AlterUniqueTogether(
            name='gametric',
            unique_together=set([('article', 'date', 'type')]),
        ),
        migrations.AlterModelOptions(
            name='gametric',
            options={'db_table': 'metrics_metric', 'ordering': ('date',)},
        ),
        migrations.RenameField(
            model_name='GAMetric',
            old_name='type',
            new_name='period',
        ),
        migrations.AddField(
            model_name='gametric',
            name='source',
            field=models.CharField(choices=[('ga', 'Google Analytics'), ('hw', 'Highwire')], default='ga', max_length=2),
        ),
        migrations.AlterField(
            model_name='gametric',
            name='period',
            field=models.CharField(choices=[('day', 'Daily'), ('month', 'Monthly'), ('ever', 'All time')], max_length=10),
        ),
        migrations.RenameModel(
            old_name='gametric',
            new_name='metric',
        ),
        migrations.AlterField(
            model_name='metric',
            name='source',
            field=models.CharField(choices=[('ga', 'Google Analytics'), ('hw', 'Highwire')], max_length=2),
        ),
        migrations.AlterField(
            model_name='metric',
            name='abstract',
            field=models.PositiveIntegerField(help_text='article abstract page views'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='digest',
            field=models.PositiveIntegerField(help_text='article digest page views'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='full',
            field=models.PositiveIntegerField(help_text='article page views'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='pdf',
            field=models.PositiveIntegerField(help_text='pdf downloads'),
        ),
        migrations.AddField(
            model_name='metric',
            name='datetime_record_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metric',
            name='datetime_record_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='abstract',
            field=models.PositiveIntegerField(help_text='article abstract page views'),
        ),
        migrations.AlterUniqueTogether(
            name='metric',
            unique_together=set([('article', 'date', 'period', 'source')]),
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField()),
                ('source', models.CharField(choices=[('scopus', "Elsevier's Scopus"), ('crossref', 'Crossref'), ('pubmed', 'PubMed Central')], max_length=10)),
                ('source_id', models.CharField(max_length=255)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article_metrics.Article')),
            ],
            options={
                'db_table': 'metrics_citation',
                'ordering': ('source',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='citation',
            unique_together=set([('article', 'source')]),
        ),
        migrations.AddField(
            model_name='article',
            name='pmcid',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='article',
            name='pmid',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='doi',
            field=models.CharField(help_text='article identifier', max_length=255, unique=True),
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'db_table': 'metrics_article', 'ordering': ('-doi',)},
        ),
        migrations.AlterModelOptions(
            name='citation',
            options={'db_table': 'metrics_citation', 'ordering': ('-num',)},
        ),
        migrations.AlterField(
            model_name='article',
            name='doi',
            field=models.CharField(help_text='article identifier', max_length=255, unique=True, validators=[article_metrics.models.validate_doi]),
        ),
        migrations.AddField(
            model_name='citation',
            name='datetime_record_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citation',
            name='datetime_record_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='citation',
            name='source',
            field=models.CharField(choices=[('crossref', 'Crossref'), ('pubmed', 'PubMed Central'), ('scopus', 'Scopus')], max_length=10),
        ),
        migrations.AlterField(
            model_name='article',
            name='doi',
            field=models.CharField(help_text='article identifier', max_length=255, unique=True, validators=[article_metrics.models.validate_doi]),
        ),
        migrations.AlterField(
            model_name='citation',
            name='source',
            field=models.CharField(choices=[('crossref', 'Crossref'), ('pubmed', 'PubMed Central'), ('scopus', 'Scopus')], max_length=10),
        ),
        migrations.AlterField(
            model_name='metric',
            name='date',
            field=models.CharField(blank=True, help_text="the date this metric is for in YYYY-MM-DD, YYYY-MM and YYYY formats or None for 'all time'", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='digest',
            field=models.PositiveIntegerField(help_text='article digest page views'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='full',
            field=models.PositiveIntegerField(help_text='article page views'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='pdf',
            field=models.PositiveIntegerField(help_text='pdf downloads'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='period',
            field=models.CharField(choices=[('day', 'Daily'), ('month', 'Monthly'), ('ever', 'All time')], max_length=10),
        ),
        migrations.AlterField(
            model_name='metric',
            name='source',
            field=models.CharField(choices=[('ga', 'Google Analytics'), ('hw', 'Highwire')], max_length=2),
        ),
    ]
