# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-01-25 17:58


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0007_auto_20150925_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField()),
                ('source', models.CharField(choices=[(b'scopus', b"Elsevier's Scopus"), (b'crossref', b'Crossref'), (b'pubmed', b'PubMed Central')], max_length=10)),
                ('source_id', models.CharField(max_length=255)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrics.Article')),
            ],
            options={
                'ordering': ('source',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='citation',
            unique_together=set([('article', 'source')]),
        ),
    ]
