# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-02-24 06:33


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_metrics', '0011_auto_20170201_1835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citation',
            options={
                'db_table': 'metrics_citation',
                'ordering': ('-num',)
            },
        ),
    ]
